apiVersion: v1
kind: Secret
metadata:
  name: 15-luis-valle-db-secret
  namespace: 15-luis-valle-namespace
type: Opaque
data:
  # Estos valores deben ser codificados en base64
  # echo -n 'neondb_owner' | base64
  db-username: bmVvbmRiX293bmVy
  # echo -n 'npg_yYaKwc5E6gsr' | base64
  db-password: bXBnX3lZYUt3YzVFNmdzcg==